<?php
return [
  'remote_server' => 'news.example.com',
  'remote_port' => '119',
  'remote_ssl' => '0',
  'remote_auth_user' => 'username',
  'remote_auth_pass' => 'password',
  'enable_nntp' => '1',
  'local_server' => '127.0.0.1',
  'local_port' => '119',
  'local_ssl_port' => '',
  'enable_all_networks' => '1',
  'server_auth_user' => 'localuser',
  'server_auth_pass' => '<local_password>',
  'rslight_title' => 'New Rocksolid Light Install',
  'title_full' => 'rslight',
  'hide_email' => '1',
  'email_tail' => '@example.com',
  'anonusername' => 'anonymous',
  'anonuserpass' => '<anonymous_password>',
  'timezone' => '0',
  'default_content' => '/rocksolid/index.php',
  'readonly' => '',
  'anonuser' => '1',
  'organization' => 'Unconfigured rslight site',
  'postfooter' => 'Unconfigured rslight site',
  'synchronet' => '',
  'rate_limit' => '12',
  'auto_create' => '',
  'verify_email' => '1',
  'no_verify' => '.i2p .onion',
  'auto_return' => '',
  'overboard_noshow' => 'rocksolid.test',
  'spamassassin' => '',
  'spamc' => 'spamc',
  'spamgroup' => 'rocksolid.spam',
  'php_exec' => 'php',
  'tac' => 'tail -r',
  'webserver_user' => '<webserver_user>',
  'enable_nocem' => '1',
  'nocem_groups' => 'rocksolid.spam',
  'expire_days' => '0',
  'pathhost' => 'unconfigured',
  'thissitekey' => '<site_key>'
];
?>
