<?php
echo '<center>';
echo '<font size="1em">';
echo '<i>rocksolid light</i> '.$rslight_version;
echo '<br />';
echo '<a href="https://github.com/novabbs/rocksolid-light" target=_blank>clearnet</a>';
echo '<a href="http://rslight.i2p/getrslight" target=_blank>i2p</a>';
echo '<a href="http://git.fuwafuwaqtlkkxwc.onion/novabbs/rocksolid-light" target=_blank>tor</a>';
echo '</font>';
echo '</center>';
?>
